language: node_js
node_js:
  - "8.12.0"
jobs:
  include:
    - stage: test
      name: "Test"
      script: yarn test
    - stage: release
      name: "Release"
      deploy:
        on:
          branch: /^(release)\/(.+)$/
        provider: script
        skip_cleanup: true
        script: yarn release

cache: yarn