language: node_js
node_js:
  - "8.12.0"
jobs:
  include:
    - stage: test
      script: yarn test
    - stage: deploy

deploy:
  provider: script
  skip_cleanup: true
  script: yarn release
cache: yarn